#!/usr/bin/env python3
"""Build the offline Unicode emoji catalog used by the IME."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "app/src/main/res/raw/emoji_catalog.tsv"
TONES = ["🏻", "🏼", "🏽", "🏾", "🏿"]


def tones(base: str) -> str:
    return "|".join(base + tone for tone in TONES)


# glyph, category, keywords, optional variants
RAW = []


def add(glyph, category, keywords, variants=""):
    RAW.append((glyph, category, keywords, variants))


# Smileys & Emotion
for item in [
    ("😀", "grinning grin happy smile face laugh"),
    ("😃", "smiley happy smile face open"),
    ("😄", "smile happy laugh face joy"),
    ("😁", "beaming grin happy smile teeth"),
    ("😆", "laughing satisfied happy xd"),
    ("😅", "sweat smile nervous relief"),
    ("😂", "joy tears laugh lol crying happy"),
    ("🤣", "rofl rolling laugh funny"),
    ("😊", "blush smile happy kind"),
    ("😇", "innocent angel halo smile"),
    ("🙂", "slight smile happy"),
    ("😉", "wink flirt joke"),
    ("😍", "heart eyes love crush"),
    ("🥰", "smiling hearts love adore"),
    ("😘", "kiss blow love"),
    ("😗", "kiss face"),
    ("😙", "kiss smile"),
    ("😚", "kiss closed eyes"),
    ("😋", "yum tasty delicious tongue"),
    ("😛", "tongue playful"),
    ("😜", "wink tongue joke"),
    ("🤪", "zany goofy crazy"),
    ("😝", "squint tongue"),
    ("🤑", "money mouth rich"),
    ("🤗", "hug hugging hands"),
    ("🤭", "hand over mouth oops"),
    ("🤫", "shush quiet secret"),
    ("🤔", "thinking think hmm"),
    ("🤐", "zipper mouth quiet"),
    ("🤨", "raised eyebrow skeptic"),
    ("😐", "neutral face meh"),
    ("😑", "expressionless blank"),
    ("😶", "no mouth silent"),
    ("😏", "smirk sly"),
    ("😒", "unamused annoyed"),
    ("🙄", "eye roll annoyed"),
    ("😬", "grimace awkward"),
    ("🤥", "lying pinocchio"),
    ("😌", "relieved calm"),
    ("😔", "pensive sad"),
    ("😪", "sleepy tired"),
    ("🤤", "drooling hungry"),
    ("😴", "sleeping sleep zzz tired"),
    ("😷", "mask sick medical"),
    ("🤒", "thermometer sick fever"),
    ("🤕", "bandage hurt injured"),
    ("🤢", "nauseated sick"),
    ("🤮", "vomit sick"),
    ("🤧", "sneeze sick"),
    ("🥵", "hot heat sweating"),
    ("🥶", "cold freezing"),
    ("🥴", "woozy dizzy"),
    ("😵", "dizzy dead"),
    ("🤯", "exploding head mind blown"),
    ("🤠", "cowboy hat"),
    ("🥳", "party celebrate birthday"),
    ("😎", "cool sunglasses"),
    ("🤓", "nerd glasses"),
    ("🧐", "monocle inspect"),
    ("😕", "confused sad"),
    ("😟", "worried sad"),
    ("🙁", "frown sad"),
    ("😮", "open mouth surprise"),
    ("😯", "hushed surprise"),
    ("😲", "astonished shock"),
    ("😳", "flushed embarrassed"),
    ("🥺", "pleading puppy eyes please"),
    ("😦", "frown open mouth"),
    ("😧", "anguished"),
    ("😨", "fearful scared"),
    ("😰", "anxious sweat"),
    ("😥", "sad but relieved"),
    ("😢", "cry sad tear"),
    ("😭", "sob cry sad tears"),
    ("😱", "scream fear shock"),
    ("😖", "confounded"),
    ("😣", "persevere"),
    ("😞", "disappointed sad"),
    ("😓", "downcast sweat"),
    ("😩", "weary tired"),
    ("😫", "tired"),
    ("🥱", "yawn sleepy"),
    ("😤", "triumph huff"),
    ("😡", "angry pouting mad rage"),
    ("😠", "angry mad"),
    ("🤬", "swearing cursing mad"),
    ("😈", "smiling devil"),
    ("👿", "angry devil"),
    ("💀", "skull dead"),
    ("☠️", "skull crossbones dead"),
    ("💩", "poop poo"),
    ("🤡", "clown"),
    ("👹", "ogre"),
    ("👺", "goblin"),
    ("👻", "ghost halloween"),
    ("👽", "alien ufo"),
    ("👾", "alien monster game"),
    ("🤖", "robot"),
    ("😺", "cat smile"),
    ("😸", "cat grin"),
    ("😹", "cat joy tears"),
    ("😻", "cat heart eyes love"),
    ("😼", "cat smirk"),
    ("😽", "cat kiss"),
    ("🙀", "cat scream"),
    ("😿", "cat cry sad"),
    ("😾", "cat pouting"),
    ("🙈", "see no evil monkey"),
    ("🙉", "hear no evil monkey"),
    ("🙊", "speak no evil monkey"),
    ("💋", "kiss mark lips"),
    ("💌", "love letter"),
    ("💘", "cupid heart arrow love"),
    ("💝", "heart ribbon gift love"),
    ("💖", "sparkling heart love"),
    ("💗", "growing heart love"),
    ("💓", "beating heart love"),
    ("💞", "revolving hearts love"),
    ("💕", "two hearts love"),
    ("💟", "heart decoration"),
    ("❣️", "heart exclamation love"),
    ("💔", "broken heart sad love"),
    ("❤️", "red heart love"),
    ("🧡", "orange heart love"),
    ("💛", "yellow heart love"),
    ("💚", "green heart love"),
    ("💙", "blue heart love"),
    ("💜", "purple heart love"),
    ("🤎", "brown heart"),
    ("🖤", "black heart"),
    ("🤍", "white heart"),
    ("💯", "hundred score perfect"),
    ("💢", "anger"),
    ("💥", "collision boom"),
    ("💫", "dizzy star"),
    ("💦", "sweat drops"),
    ("💨", "dash wind"),
    ("🕳️", "hole"),
    ("💣", "bomb"),
    ("💬", "speech balloon talk"),
    ("👁️‍🗨️", "eye speech bubble"),
    ("💭", "thought balloon think"),
    ("💤", "zzz sleep"),
]:
    add(item[0], "smileys", item[1])

# People & Body
for item in [
    ("👋", "wave hello hi bye hand", tones("👋")),
    ("🤚", "raised back hand", tones("🤚")),
    ("🖐️", "hand splayed", tones("🖐️")),
    ("✋", "raised hand stop", tones("✋")),
    ("🖖", "vulcan salute", tones("🖖")),
    ("👌", "ok hand okay", tones("👌")),
    ("🤌", "pinched fingers", tones("🤌")),
    ("🤏", "pinching hand small", tones("🤏")),
    ("✌", "victory peace", tones("✌")),
    ("🤞", "crossed fingers luck", tones("🤞")),
    ("🤟", "love you gesture", tones("🤟")),
    ("🤘", "horns rock", tones("🤘")),
    ("🤙", "call me shaka", tones("🤙")),
    ("👈", "backhand left", tones("👈")),
    ("👉", "backhand right", tones("👉")),
    ("👆", "backhand up", tones("👆")),
    ("👇", "backhand down", tones("👇")),
    ("☝️", "index up", tones("☝️")),
    ("👍", "thumbs up like yes good", tones("👍")),
    ("👎", "thumbs down no dislike", tones("👎")),
    ("✊", "fist raised", tones("✊")),
    ("👊", "punch fist", tones("👊")),
    ("🤛", "left facing fist", tones("🤛")),
    ("🤜", "right facing fist", tones("🤜")),
    ("👏", "clap applause", tones("👏")),
    ("🙌", "raising hands hooray", tones("🙌")),
    ("👐", "open hands", tones("👐")),
    ("🤲", "palms up", tones("🤲")),
    ("🤝", "handshake deal"),
    ("🙏", "folded hands pray thanks please namaste", tones("🙏")),
    ("✍️", "writing hand", tones("✍️")),
    ("💅", "nail polish", tones("💅")),
    ("🤳", "selfie", tones("🤳")),
    ("💪", "flex muscle strong", tones("💪")),
    ("🦾", "mechanical arm"),
    ("🦿", "mechanical leg"),
    ("🦵", "leg", tones("🦵")),
    ("🦶", "foot", tones("🦶")),
    ("👂", "ear", tones("👂")),
    ("👃", "nose", tones("👃")),
    ("🧠", "brain"),
    ("🦷", "tooth"),
    ("🦴", "bone"),
    ("👀", "eyes look"),
    ("👁️", "eye"),
    ("👅", "tongue"),
    ("👄", "mouth lips"),
    ("👶", "baby infant", tones("👶")),
    ("👧", "girl child", tones("👧")),
    ("🧒", "child", tones("🧒")),
    ("👦", "boy child", tones("👦")),
    ("👩", "woman female", tones("👩")),
    ("🧑", "person adult", tones("🧑")),
    ("👨", "man male", tones("👨")),
    ("👩‍🦰", "woman red hair"),
    ("👨‍🦰", "man red hair"),
    ("👩‍🦱", "woman curly hair"),
    ("👨‍🦱", "man curly hair"),
    ("👩‍🦳", "woman white hair"),
    ("👨‍🦳", "man white hair"),
    ("👩‍🦲", "woman bald"),
    ("👨‍🦲", "man bald"),
    ("👱‍♀️", "woman blond hair"),
    ("👱‍♂️", "man blond hair"),
    ("🧔", "person beard"),
    ("👵", "old woman grandma", tones("👵")),
    ("👴", "old man grandpa", tones("👴")),
    ("🙍‍♀️", "woman frowning"),
    ("🙍‍♂️", "man frowning"),
    ("🙎‍♀️", "woman pouting"),
    ("🙎‍♂️", "man pouting"),
    ("🙅‍♀️", "woman no gesture"),
    ("🙅‍♂️", "man no gesture"),
    ("🙆‍♀️", "woman ok gesture"),
    ("🙆‍♂️", "man ok gesture"),
    ("💁‍♀️", "woman tipping hand"),
    ("💁‍♂️", "man tipping hand"),
    ("🙋‍♀️", "woman raising hand"),
    ("🙋‍♂️", "man raising hand"),
    ("🧏‍♀️", "deaf woman"),
    ("🧏‍♂️", "deaf man"),
    ("🙇‍♀️", "woman bowing"),
    ("🙇‍♂️", "man bowing"),
    ("🤦‍♀️", "woman facepalm"),
    ("🤦‍♂️", "man facepalm"),
    ("🤷‍♀️", "woman shrug"),
    ("🤷‍♂️", "man shrug"),
    ("👩‍⚕️", "woman health worker doctor"),
    ("👨‍⚕️", "man health worker doctor"),
    ("👩‍🎓", "woman student"),
    ("👨‍🎓", "man student"),
    ("👩‍🏫", "woman teacher"),
    ("👨‍🏫", "man teacher"),
    ("👩‍💻", "woman technologist coder"),
    ("👨‍💻", "man technologist coder"),
    ("👩‍🍳", "woman cook"),
    ("👨‍🍳", "man cook"),
    ("👩‍🌾", "woman farmer"),
    ("👨‍🌾", "man farmer"),
    ("👮‍♀️", "woman police"),
    ("👮‍♂️", "man police"),
    ("👷‍♀️", "woman construction worker"),
    ("👷‍♂️", "man construction worker"),
    ("💂‍♀️", "woman guard"),
    ("💂‍♂️", "man guard"),
    ("🕵️‍♀️", "woman detective"),
    ("🕵️‍♂️", "man detective"),
    ("👩‍🚒", "woman firefighter"),
    ("👨‍🚒", "man firefighter"),
    ("👩‍✈️", "woman pilot"),
    ("👨‍✈️", "man pilot"),
    ("👸", "princess", tones("👸")),
    ("🤴", "prince", tones("🤴")),
    ("🦸‍♀️", "woman superhero"),
    ("🦸‍♂️", "man superhero"),
    ("🧛‍♀️", "woman vampire"),
    ("🧛‍♂️", "man vampire"),
    ("🧜‍♀️", "mermaid"),
    ("🧚‍♀️", "woman fairy"),
    ("👼", "baby angel"),
    ("🎅", "santa"),
    ("🤶", "mrs claus"),
    ("🧙‍♂️", "man mage wizard"),
    ("🧙‍♀️", "woman mage wizard"),
    ("💃", "woman dancing", tones("💃")),
    ("🕺", "man dancing", tones("🕺")),
    ("🕴️", "person in suit levitating"),
    ("👯‍♀️", "women with bunny ears"),
    ("🚶‍♀️", "woman walking"),
    ("🚶‍♂️", "man walking"),
    ("🏃‍♀️", "woman running"),
    ("🏃‍♂️", "man running"),
    ("🧍‍♀️", "woman standing"),
    ("🧍‍♂️", "man standing"),
    ("🧎‍♀️", "woman kneeling"),
    ("🧎‍♂️", "man kneeling"),
    ("👩‍🦯", "woman with probing cane"),
    ("👨‍🦯", "man with probing cane"),
    ("👩‍🦼", "woman motorized wheelchair"),
    ("👨‍🦼", "man motorized wheelchair"),
    ("👩‍🦽", "woman manual wheelchair"),
    ("👨‍🦽", "man manual wheelchair"),
    ("💑", "couple with heart"),
    ("👩‍❤️‍👨", "couple woman man heart"),
    ("👨‍❤️‍👨", "couple man man heart"),
    ("👩‍❤️‍👩", "couple woman woman heart"),
    ("💏", "kiss couple"),
    ("👪", "family"),
    ("👨‍👩‍👧", "family man woman girl"),
    ("👨‍👩‍👧‍👦", "family man woman girl boy"),
    ("👩‍👦", "family woman boy"),
    ("👨‍👦", "family man boy"),
    ("🗣️", "speaking head"),
    ("👤", "bust silhouette"),
    ("👥", "busts silhouette people"),
    ("🫂", "people hugging"),
    ("👣", "footprints"),
]:
    add(item[0], "people", item[1], item[2] if len(item) > 2 else "")

# Animals & Nature
for item in [
    ("🐶", "dog puppy pet animal"),
    ("🐱", "cat kitten pet animal"),
    ("🐭", "mouse animal"),
    ("🐹", "hamster pet"),
    ("🐰", "rabbit bunny"),
    ("🦊", "fox"),
    ("🐻", "bear"),
    ("🐼", "panda"),
    ("🐻‍❄️", "polar bear"),
    ("🐨", "koala"),
    ("🐯", "tiger"),
    ("🦁", "lion"),
    ("🐮", "cow"),
    ("🐷", "pig"),
    ("🐸", "frog"),
    ("🐵", "monkey"),
    ("🙈", "see no evil monkey"),
    ("🐔", "chicken hen"),
    ("🐧", "penguin"),
    ("🐦", "bird"),
    ("🐤", "baby chick"),
    ("🐣", "hatching chick"),
    ("🐥", "front chick"),
    ("🦆", "duck"),
    ("🦅", "eagle"),
    ("🦉", "owl"),
    ("🦇", "bat"),
    ("🐺", "wolf"),
    ("🐗", "boar"),
    ("🐴", "horse"),
    ("🦄", "unicorn"),
    ("🐝", "bee honey"),
    ("🪱", "worm"),
    ("🐛", "bug"),
    ("🦋", "butterfly"),
    ("🐌", "snail"),
    ("🐞", "ladybug"),
    ("🐜", "ant"),
    ("🪰", "fly"),
    ("🪲", "beetle"),
    ("🪳", "cockroach"),
    ("🦟", "mosquito"),
    ("🦗", "cricket"),
    ("🕷️", "spider"),
    ("🕸️", "spider web"),
    ("🦂", "scorpion"),
    ("🐢", "turtle"),
    ("🐍", "snake"),
    ("🦎", "lizard"),
    ("🦖", "t-rex dinosaur"),
    ("🦕", "sauropod dinosaur"),
    ("🐙", "octopus"),
    ("🦑", "squid"),
    ("🦐", "shrimp"),
    ("🦞", "lobster"),
    ("🦀", "crab"),
    ("🐡", "blowfish"),
    ("🐠", "tropical fish"),
    ("🐟", "fish"),
    ("🐬", "dolphin"),
    ("🐳", "whale spout"),
    ("🐋", "whale"),
    ("🦈", "shark"),
    ("🐊", "crocodile"),
    ("🐅", "tiger"),
    ("🐆", "leopard"),
    ("🦓", "zebra"),
    ("🦍", "gorilla"),
    ("🦧", "orangutan"),
    ("🦣", "mammoth"),
    ("🐘", "elephant"),
    ("🦛", "hippo"),
    ("🦏", "rhino"),
    ("🐪", "camel"),
    ("🐫", "two hump camel"),
    ("🦒", "giraffe"),
    ("🦘", "kangaroo"),
    ("🦬", "bison"),
    ("🐃", "water buffalo"),
    ("🐂", "ox"),
    ("🐄", "cow"),
    ("🐎", "racehorse"),
    ("🐖", "pig"),
    ("🐏", "ram"),
    ("🐑", "ewe sheep"),
    ("🦙", "llama"),
    ("🐐", "goat"),
    ("🦌", "deer"),
    ("🐕", "dog"),
    ("🐩", "poodle"),
    ("🦮", "guide dog"),
    ("🐕‍🦺", "service dog"),
    ("🐈", "cat"),
    ("🐈‍⬛", "black cat"),
    ("🪶", "feather"),
    ("🐓", "rooster"),
    ("🦃", "turkey"),
    ("🦤", "dodo"),
    ("🦚", "peacock"),
    ("🦜", "parrot"),
    ("🦢", "swan"),
    ("🦩", "flamingo"),
    ("🕊️", "dove peace"),
    ("🐇", "rabbit"),
    ("🦝", "raccoon"),
    ("🦨", "skunk"),
    ("🦡", "badger"),
    ("🦫", "beaver"),
    ("🦦", "otter"),
    ("🦥", "sloth"),
    ("🐁", "mouse"),
    ("🐀", "rat"),
    ("🐿️", "chipmunk"),
    ("🦔", "hedgehog"),
    ("🐾", "paw prints"),
    ("🐉", "dragon"),
    ("🐲", "dragon face"),
    ("🌵", "cactus"),
    ("🎄", "christmas tree"),
    ("🌲", "evergreen tree"),
    ("🌳", "deciduous tree"),
    ("🌴", "palm tree"),
    ("🪵", "wood"),
    ("🌱", "seedling plant"),
    ("🌿", "herb leaf"),
    ("☘️", "shamrock"),
    ("🍀", "four leaf clover luck"),
    ("🎍", "pine decoration"),
    ("🪴", "potted plant"),
    ("🎋", "tanabata tree"),
    ("🍃", "leaf flutter"),
    ("🍂", "fallen leaf"),
    ("🍁", "maple leaf"),
    ("🍄", "mushroom"),
    ("🐚", "shell"),
    ("🪨", "rock"),
    ("🌾", "sheaf rice"),
    ("💐", "bouquet flowers"),
    ("🌷", "tulip"),
    ("🌹", "rose flower"),
    ("🥀", "wilted flower"),
    ("🌺", "hibiscus"),
    ("🌸", "cherry blossom"),
    ("🌼", "blossom"),
    ("🌻", "sunflower"),
    ("🌞", "sun face"),
    ("🌝", "full moon face"),
    ("🌛", "first quarter moon face"),
    ("🌜", "last quarter moon face"),
    ("🌚", "new moon face"),
    ("🌕", "full moon"),
    ("🌖", "waning gibbous moon"),
    ("🌗", "last quarter moon"),
    ("🌘", "waning crescent moon"),
    ("🌑", "new moon"),
    ("🌒", "waxing crescent moon"),
    ("🌓", "first quarter moon"),
    ("🌔", "waxing gibbous moon"),
    ("🌙", "crescent moon night"),
    ("🌎", "earth americas world"),
    ("🌍", "earth africa europe world"),
    ("🌏", "earth asia australia world"),
    ("🪐", "ringed planet saturn"),
    ("💫", "dizzy"),
    ("⭐", "star"),
    ("🌟", "glowing star"),
    ("✨", "sparkles shine"),
    ("⚡", "zap lightning"),
    ("☄️", "comet"),
    ("💥", "boom"),
    ("🔥", "fire flame hot"),
    ("🌪️", "tornado"),
    ("🌈", "rainbow"),
    ("☀️", "sun sunny weather"),
    ("🌤️", "sun behind small cloud"),
    ("⛅", "sun behind cloud"),
    ("🌥️", "sun behind large cloud"),
    ("☁️", "cloud"),
    ("🌦️", "sun behind rain cloud"),
    ("🌧️", "cloud rain"),
    ("⛈️", "cloud lightning rain"),
    ("🌩️", "cloud lightning"),
    ("🌨️", "cloud snow"),
    ("❄️", "snowflake cold"),
    ("☃️", "snowman"),
    ("⛄", "snowman without snow"),
    ("🌬️", "wind face"),
    ("💨", "dash"),
    ("💧", "droplet water"),
    ("💦", "sweat droplets"),
    ("☔", "umbrella rain"),
    ("☂️", "umbrella"),
    ("🌊", "ocean wave water"),
    ("🌫️", "fog"),
]:
    add(item[0], "animals", item[1])

# Food & Drink
for item in [
    ("🍎", "apple red fruit food"),
    ("🍏", "green apple fruit"),
    ("🍐", "pear fruit"),
    ("🍊", "tangerine orange fruit"),
    ("🍋", "lemon fruit"),
    ("🍌", "banana fruit"),
    ("🍉", "watermelon fruit"),
    ("🍇", "grapes fruit"),
    ("🍓", "strawberry fruit"),
    ("🫐", "blueberries fruit"),
    ("🍈", "melon fruit"),
    ("🍒", "cherries fruit"),
    ("🍑", "peach fruit"),
    ("🥭", "mango fruit"),
    ("🍍", "pineapple fruit"),
    ("🥥", "coconut"),
    ("🥝", "kiwi fruit"),
    ("🍅", "tomato"),
    ("🍆", "eggplant"),
    ("🥑", "avocado"),
    ("🥦", "broccoli"),
    ("🥬", "leafy green"),
    ("🥒", "cucumber"),
    ("🌶️", "hot pepper chili"),
    ("🫑", "bell pepper"),
    ("🌽", "corn"),
    ("🥕", "carrot"),
    ("🫒", "olive"),
    ("🧄", "garlic"),
    ("🧅", "onion"),
    ("🥔", "potato"),
    ("🍠", "roasted sweet potato"),
    ("🥐", "croissant bread"),
    ("🥯", "bagel"),
    ("🍞", "bread"),
    ("🥖", "baguette"),
    ("🥨", "pretzel"),
    ("🧀", "cheese"),
    ("🥚", "egg"),
    ("🍳", "cooking fried egg"),
    ("🧈", "butter"),
    ("🥞", "pancakes"),
    ("🧇", "waffle"),
    ("🥓", "bacon"),
    ("🥩", "cut of meat"),
    ("🍗", "poultry leg chicken"),
    ("🍖", "meat on bone"),
    ("🦴", "bone"),
    ("🌭", "hot dog"),
    ("🍔", "hamburger burger food"),
    ("🍟", "fries french"),
    ("🍕", "pizza food"),
    ("🫓", "flatbread"),
    ("🥪", "sandwich"),
    ("🥙", "stuffed flatbread"),
    ("🧆", "falafel"),
    ("🌮", "taco"),
    ("🌯", "burrito"),
    ("🫔", "tamale"),
    ("🥗", "green salad"),
    ("🥘", "shallow pan of food"),
    ("🫕", "fondue"),
    ("🍝", "spaghetti pasta"),
    ("🍜", "steaming bowl ramen noodles"),
    ("🍲", "pot of food"),
    ("🍛", "curry rice"),
    ("🍣", "sushi"),
    ("🍱", "bento"),
    ("🥟", "dumpling momo"),
    ("🦪", "oyster"),
    ("🍤", "fried shrimp"),
    ("🍙", "rice ball"),
    ("🍚", "cooked rice food"),
    ("🍘", "rice cracker"),
    ("🍥", "fish cake"),
    ("🥠", "fortune cookie"),
    ("🥮", "moon cake"),
    ("🍢", "oden"),
    ("🍡", "dango"),
    ("🍧", "shaved ice"),
    ("🍨", "ice cream"),
    ("🍦", "soft ice cream"),
    ("🥧", "pie"),
    ("🧁", "cupcake"),
    ("🍰", "cake shortcake dessert"),
    ("🎂", "birthday cake"),
    ("🍮", "custard"),
    ("🍭", "lollipop"),
    ("🍬", "candy"),
    ("🍫", "chocolate bar"),
    ("🍿", "popcorn"),
    ("🍩", "doughnut donut"),
    ("🍪", "cookie"),
    ("🌰", "chestnut"),
    ("🥜", "peanuts"),
    ("🍯", "honey pot"),
    ("🥛", "glass of milk"),
    ("🍼", "baby bottle"),
    ("🫖", "teapot"),
    ("☕", "coffee tea hot drink"),
    ("🍵", "teacup"),
    ("🧃", "beverage box juice"),
    ("🥤", "cup with straw"),
    ("🧋", "bubble tea"),
    ("🍶", "sake"),
    ("🍺", "beer mug drink"),
    ("🍻", "clinking beer mugs"),
    ("🥂", "clinking glasses"),
    ("🍷", "wine glass"),
    ("🥃", "tumbler glass"),
    ("🍸", "cocktail"),
    ("🍹", "tropical drink"),
    ("🧉", "mate"),
    ("🍾", "champagne bottle"),
    ("🧊", "ice cube"),
    ("🥄", "spoon"),
    ("🍴", "fork knife"),
    ("🍽️", "fork knife plate"),
    ("🥣", "bowl spoon"),
    ("🥡", "takeout box"),
    ("🥢", "chopsticks"),
    ("🧂", "salt"),
]:
    add(item[0], "food", item[1])

# Travel & Places
for item in [
    ("🚗", "car automobile travel"),
    ("🚕", "taxi cab"),
    ("🚙", "sport utility vehicle"),
    ("🚌", "bus"),
    ("🚎", "trolleybus"),
    ("🏎️", "racing car"),
    ("🚓", "police car"),
    ("🚑", "ambulance"),
    ("🚒", "fire engine"),
    ("🚐", "minibus"),
    ("🛻", "pickup truck"),
    ("🚚", "delivery truck"),
    ("🚛", "articulated lorry"),
    ("🚜", "tractor"),
    ("🦯", "probing cane"),
    ("🦽", "manual wheelchair"),
    ("🦼", "motorized wheelchair"),
    ("🛴", "kick scooter"),
    ("🚲", "bicycle bike"),
    ("🛵", "motor scooter"),
    ("🏍️", "motorcycle"),
    ("🛺", "auto rickshaw tempo"),
    ("🚨", "police car light"),
    ("🚔", "oncoming police car"),
    ("🚍", "oncoming bus"),
    ("🚘", "oncoming automobile"),
    ("🚖", "oncoming taxi"),
    ("🚡", "aerial tramway"),
    ("🚠", "mountain cableway"),
    ("🚟", "suspension railway"),
    ("🚃", "railway car"),
    ("🚋", "tram car"),
    ("🚞", "mountain railway"),
    ("🚝", "monorail"),
    ("🚄", "high speed train"),
    ("🚅", "bullet train"),
    ("🚈", "light rail"),
    ("🚂", "locomotive"),
    ("🚆", "train"),
    ("🚇", "metro"),
    ("🚊", "tram"),
    ("🚉", "station"),
    ("✈️", "airplane plane flight travel"),
    ("🛫", "airplane departure"),
    ("🛬", "airplane arrival"),
    ("🛩️", "small airplane"),
    ("💺", "seat"),
    ("🛰️", "satellite"),
    ("🚀", "rocket space"),
    ("🛸", "flying saucer ufo"),
    ("🚁", "helicopter"),
    ("🛶", "canoe"),
    ("⛵", "sailboat"),
    ("🚤", "speedboat"),
    ("🛥️", "motor boat"),
    ("🛳️", "passenger ship"),
    ("⛴️", "ferry"),
    ("🚢", "ship"),
    ("⚓", "anchor"),
    ("⛽", "fuel pump"),
    ("🚧", "construction"),
    ("🚦", "vertical traffic light"),
    ("🚥", "horizontal traffic light"),
    ("🚏", "bus stop"),
    ("🗺️", "world map"),
    ("🗿", "moai"),
    ("🗽", "statue of liberty"),
    ("🗼", "tokyo tower"),
    ("🏰", "castle"),
    ("🏯", "japanese castle"),
    ("🏟️", "stadium"),
    ("🎡", "ferris wheel"),
    ("🎢", "roller coaster"),
    ("🎠", "carousel horse"),
    ("⛲", "fountain"),
    ("⛱️", "umbrella on ground"),
    ("🏖️", "beach umbrella"),
    ("🏝️", "desert island"),
    ("🏜️", "desert"),
    ("🌋", "volcano"),
    ("⛰️", "mountain"),
    ("🏔️", "snow capped mountain"),
    ("🗻", "mount fuji"),
    ("🏕️", "camping"),
    ("⛺", "tent"),
    ("🏠", "house home"),
    ("🏡", "house garden"),
    ("🏘️", "houses"),
    ("🏚️", "derelict house"),
    ("🏗️", "building construction"),
    ("🏭", "factory"),
    ("🏢", "office building"),
    ("🏬", "department store"),
    ("🏣", "japanese post office"),
    ("🏤", "post office"),
    ("🏥", "hospital"),
    ("🏦", "bank"),
    ("🏨", "hotel"),
    ("🏪", "convenience store"),
    ("🏫", "school"),
    ("🏩", "love hotel"),
    ("💒", "wedding"),
    ("🏛️", "classical building"),
    ("⛪", "church"),
    ("🕌", "mosque"),
    ("🕍", "synagogue"),
    ("🛕", "hindu temple"),
    ("🕋", "kaaba"),
    ("⛩️", "shinto shrine"),
    ("🛤️", "railway track"),
    ("🛣️", "motorway"),
    ("🗾", "map of japan"),
    ("🎑", "moon viewing"),
    ("🏞️", "national park"),
    ("🌅", "sunrise"),
    ("🌄", "sunrise mountains"),
    ("🌠", "shooting star"),
    ("🎇", "sparkler"),
    ("🎆", "fireworks"),
    ("🌇", "sunset"),
    ("🌆", "cityscape dusk"),
    ("🏙️", "cityscape"),
    ("🌃", "night stars"),
    ("🌌", "milky way"),
    ("🌉", "bridge night"),
    ("🌁", "foggy"),
]:
    add(item[0], "travel", item[1])

# Activities
for item in [
    ("⚽", "soccer football ball sport"),
    ("🏀", "basketball sport"),
    ("🏈", "american football sport"),
    ("⚾", "baseball sport"),
    ("🥎", "softball"),
    ("🎾", "tennis"),
    ("🏐", "volleyball"),
    ("🏉", "rugby football"),
    ("🥏", "flying disc frisbee"),
    ("🎱", "pool 8ball"),
    ("🪀", "yo-yo"),
    ("🏓", "ping pong"),
    ("🏸", "badminton"),
    ("🏒", "ice hockey"),
    ("🏑", "field hockey"),
    ("🥍", "lacrosse"),
    ("🏏", "cricket game"),
    ("🪃", "boomerang"),
    ("🥅", "goal net"),
    ("⛳", "flag in hole golf"),
    ("🪁", "kite"),
    ("🏹", "bow arrow"),
    ("🎣", "fishing pole"),
    ("🤿", "diving mask"),
    ("🥊", "boxing glove"),
    ("🥋", "martial arts uniform"),
    ("🎽", "running shirt"),
    ("🛹", "skateboard"),
    ("🛼", "roller skate"),
    ("🛷", "sled"),
    ("⛸️", "ice skate"),
    ("🥌", "curling stone"),
    ("🎿", "skis"),
    ("⛷️", "skier"),
    ("🏂", "snowboarder"),
    ("🪂", "parachute"),
    ("🏋️‍♀️", "woman lifting weights"),
    ("🏋️‍♂️", "man lifting weights"),
    ("🤼‍♀️", "women wrestling"),
    ("🤼‍♂️", "men wrestling"),
    ("🤸‍♀️", "woman cartwheeling"),
    ("🤸‍♂️", "man cartwheeling"),
    ("⛹️‍♀️", "woman bouncing ball"),
    ("⛹️‍♂️", "man bouncing ball"),
    ("🤺", "person fencing"),
    ("🤾‍♀️", "woman handball"),
    ("🤾‍♂️", "man handball"),
    ("🏌️‍♀️", "woman golfing"),
    ("🏌️‍♂️", "man golfing"),
    ("🏇", "horse racing"),
    ("🧘‍♀️", "woman lotus yoga"),
    ("🧘‍♂️", "man lotus yoga"),
    ("🏄‍♀️", "woman surfing"),
    ("🏄‍♂️", "man surfing"),
    ("🏊‍♀️", "woman swimming"),
    ("🏊‍♂️", "man swimming"),
    ("🤽‍♀️", "woman water polo"),
    ("🤽‍♂️", "man water polo"),
    ("🚣‍♀️", "woman rowing"),
    ("🚣‍♂️", "man rowing"),
    ("🧗‍♀️", "woman climbing"),
    ("🧗‍♂️", "man climbing"),
    ("🚵‍♀️", "woman mountain biking"),
    ("🚵‍♂️", "man mountain biking"),
    ("🚴‍♀️", "woman biking"),
    ("🚴‍♂️", "man biking"),
    ("🏆", "trophy win"),
    ("🥇", "gold medal first"),
    ("🥈", "silver medal"),
    ("🥉", "bronze medal"),
    ("🏅", "sports medal"),
    ("🎖️", "military medal"),
    ("🏵️", "rosette"),
    ("🎗️", "reminder ribbon"),
    ("🎫", "ticket"),
    ("🎟️", "admission tickets"),
    ("🎪", "circus tent"),
    ("🤹‍♀️", "woman juggling"),
    ("🤹‍♂️", "man juggling"),
    ("🎭", "performing arts theater"),
    ("🩰", "ballet shoes"),
    ("🎨", "artist palette art"),
    ("🎬", "clapper board movie"),
    ("🎤", "microphone sing"),
    ("🎧", "headphone music"),
    ("🎼", "musical score"),
    ("🎹", "musical keyboard piano"),
    ("🥁", "drum"),
    ("🪘", "long drum"),
    ("🎷", "saxophone"),
    ("🎺", "trumpet"),
    ("🪗", "accordion"),
    ("🎸", "guitar music"),
    ("🪕", "banjo"),
    ("🎻", "violin"),
    ("🎲", "game die dice"),
    ("♟️", "chess pawn"),
    ("🎯", "bullseye dart"),
    ("🎳", "bowling"),
    ("🎮", "video game controller"),
    ("🎰", "slot machine"),
    ("🧩", "puzzle piece"),
]:
    add(item[0], "activities", item[1])

# Objects
for item in [
    ("💡", "light bulb idea"),
    ("🔦", "flashlight"),
    ("🏮", "red paper lantern"),
    ("🪔", "diya lamp"),
    ("📱", "mobile phone"),
    ("📲", "mobile arrow"),
    ("💻", "laptop computer"),
    ("⌨️", "keyboard"),
    ("🖥️", "desktop computer"),
    ("🖨️", "printer"),
    ("🖱️", "computer mouse"),
    ("🖲️", "trackball"),
    ("💽", "computer disk"),
    ("💾", "floppy disk"),
    ("💿", "optical disk"),
    ("📀", "dvd"),
    ("🧮", "abacus"),
    ("🎥", "movie camera"),
    ("🎞️", "film frames"),
    ("📽️", "film projector"),
    ("🎬", "clapper"),
    ("📺", "television tv"),
    ("📷", "camera photo"),
    ("📸", "camera flash"),
    ("📹", "video camera"),
    ("📼", "videocassette"),
    ("🔍", "magnifying glass left search"),
    ("🔎", "magnifying glass right search"),
    ("🕯️", "candle"),
    ("💡", "bulb"),
    ("📁", "file folder"),
    ("📂", "open file folder"),
    ("🗂️", "card index dividers"),
    ("📅", "calendar"),
    ("📆", "tear-off calendar"),
    ("🗒️", "spiral notepad"),
    ("🗓️", "spiral calendar"),
    ("📇", "card index"),
    ("📈", "chart increasing"),
    ("📉", "chart decreasing"),
    ("📊", "bar chart"),
    ("📋", "clipboard"),
    ("📌", "pushpin"),
    ("📍", "round pushpin"),
    ("📎", "paperclip"),
    ("🖇️", "linked paperclips"),
    ("📏", "straight ruler"),
    ("📐", "triangular ruler"),
    ("✂️", "scissors"),
    ("🗃️", "card file box"),
    ("🗄️", "file cabinet"),
    ("🗑️", "wastebasket"),
    ("🔒", "locked"),
    ("🔓", "unlocked"),
    ("🔏", "locked pen"),
    ("🔐", "locked key"),
    ("🔑", "key"),
    ("🗝️", "old key"),
    ("🔨", "hammer"),
    ("🪓", "axe"),
    ("⛏️", "pick"),
    ("⚒️", "hammer pick"),
    ("🛠️", "hammer wrench"),
    ("🗡️", "dagger"),
    ("⚔️", "crossed swords"),
    ("🔫", "water pistol"),
    ("🪃", "boomerang"),
    ("🏹", "bow arrow"),
    ("🛡️", "shield"),
    ("🪚", "carpentry saw"),
    ("🔧", "wrench"),
    ("🪛", "screwdriver"),
    ("🔩", "nut bolt"),
    ("⚙️", "gear"),
    ("🗜️", "clamp"),
    ("⚖️", "balance scale"),
    ("🦯", "probing cane"),
    ("🔗", "link"),
    ("⛓️", "chains"),
    ("🪝", "hook"),
    ("🧰", "toolbox"),
    ("🧲", "magnet"),
    ("🪜", "ladder"),
    ("⚗️", "alembic"),
    ("🧪", "test tube"),
    ("🧫", "petri dish"),
    ("🧬", "dna"),
    ("🔬", "microscope"),
    ("🔭", "telescope"),
    ("📡", "satellite antenna"),
    ("💉", "syringe"),
    ("🩸", "drop of blood"),
    ("💊", "pill"),
    ("🩹", "adhesive bandage"),
    ("🩺", "stethoscope"),
    ("🚪", "door"),
    ("🪞", "mirror"),
    ("🪟", "window"),
    ("🛏️", "bed"),
    ("🛋️", "couch lamp"),
    ("🪑", "chair"),
    ("🚽", "toilet"),
    ("🪠", "plunger"),
    ("🚿", "shower"),
    ("🛁", "bathtub"),
    ("🪤", "mouse trap"),
    ("🪒", "razor"),
    ("🧴", "lotion bottle"),
    ("🧷", "safety pin"),
    ("🧹", "broom"),
    ("🧺", "basket"),
    ("🧻", "roll of paper"),
    ("🪣", "bucket"),
    ("🧼", "soap"),
    ("🪥", "toothbrush"),
    ("🧽", "sponge"),
    ("🧯", "fire extinguisher"),
    ("🛒", "shopping cart"),
    ("🚬", "cigarette"),
    ("⚰️", "coffin"),
    ("🪦", "headstone"),
    ("⚱️", "funeral urn"),
    ("🗿", "moai"),
    ("🪧", "placard"),
    ("🚰", "potable water"),
    ("⌚", "watch"),
    ("⏰", "alarm clock"),
    ("⏱️", "stopwatch"),
    ("⏲️", "timer clock"),
    ("🕰️", "mantelpiece clock"),
    ("⌛", "hourglass"),
    ("⏳", "hourglass flowing"),
    ("📡", "antenna"),
    ("🔋", "battery"),
    ("🔌", "electric plug"),
    ("💻", "laptop"),
    ("🖱️", "mouse"),
    ("💸", "money with wings"),
    ("💵", "dollar banknote"),
    ("💴", "yen banknote"),
    ("💶", "euro banknote"),
    ("💷", "pound banknote"),
    ("🪙", "coin"),
    ("💰", "money bag"),
    ("💳", "credit card"),
    ("💎", "gem stone"),
    ("⚖️", "scale"),
    ("🪜", "ladder"),
    ("🧰", "toolbox"),
    ("🧲", "magnet"),
    ("🔫", "pistol"),
    ("💣", "bomb"),
    ("🔪", "kitchen knife"),
    ("🗺️", "map"),
    ("🧭", "compass"),
    ("🧱", "brick"),
    ("💈", "barber pole"),
    ("🦽", "wheelchair"),
    ("🛢️", "oil drum"),
    ("🛎️", "bellhop bell"),
    ("🧳", "luggage"),
    ("⌛", "hourglass done"),
    ("⏰", "alarm"),
    ("📡", "satellite"),
    ("📿", "prayer beads"),
    ("🧿", "nazar amulet"),
    ("💍", "ring"),
    ("💎", "gem"),
    ("📢", "loudspeaker"),
    ("📣", "megaphone"),
    ("📯", "postal horn"),
    ("🔔", "bell"),
    ("🔕", "bell slash"),
    ("🎵", "musical note"),
    ("🎶", "musical notes"),
    ("💹", "chart yen"),
    ("🏧", "atm"),
    ("🚮", "litter"),
    ("🚰", "water"),
    ("♿", "wheelchair symbol"),
    ("🚹", "mens room"),
    ("🚺", "womens room"),
    ("🚻", "restroom"),
    ("🚼", "baby symbol"),
    ("🚾", "water closet wc"),
    ("🛂", "passport control"),
    ("🛃", "customs"),
    ("🛄", "baggage claim"),
    ("🛅", "left luggage"),
    ("⚠️", "warning"),
    ("🚸", "children crossing"),
    ("⛔", "no entry"),
    ("🚫", "prohibited"),
    ("🚳", "no bicycles"),
    ("🚭", "no smoking"),
    ("🚯", "no littering"),
    ("🚱", "non-potable water"),
    ("🚷", "no pedestrians"),
    ("📵", "no mobile phones"),
    ("🔞", "no one under eighteen"),
    ("☢️", "radioactive"),
    ("☣️", "biohazard"),
    ("⬆️", "up arrow"),
    ("↗️", "up-right arrow"),
    ("➡️", "right arrow"),
    ("↘️", "down-right arrow"),
    ("⬇️", "down arrow"),
    ("↙️", "down-left arrow"),
    ("⬅️", "left arrow"),
    ("↖️", "up-left arrow"),
    ("↕️", "up-down arrow"),
    ("↔️", "left-right arrow"),
    ("↩️", "right arrow curving left"),
    ("↪️", "left arrow curving right"),
    ("⤴️", "right arrow curving up"),
    ("⤵️", "right arrow curving down"),
    ("🔃", "clockwise arrows"),
    ("🔄", "counterclockwise arrows"),
    ("🔙", "back arrow"),
    ("🔚", "end arrow"),
    ("🔛", "on arrow"),
    ("🔜", "soon arrow"),
    ("🔝", "top arrow"),
]:
    add(item[0], "objects", item[1])

# Symbols
for item in [
    ("❤️", "red heart love"),
    ("🧡", "orange heart"),
    ("💛", "yellow heart"),
    ("💚", "green heart"),
    ("💙", "blue heart"),
    ("💜", "purple heart"),
    ("🖤", "black heart"),
    ("🤍", "white heart"),
    ("🤎", "brown heart"),
    ("💔", "broken heart"),
    ("❣️", "heart exclamation"),
    ("💕", "two hearts"),
    ("💞", "revolving hearts"),
    ("💓", "beating heart"),
    ("💗", "growing heart"),
    ("💖", "sparkling heart"),
    ("💘", "heart arrow"),
    ("💝", "heart ribbon"),
    ("💟", "heart decoration"),
    ("☮️", "peace"),
    ("✝️", "latin cross"),
    ("☪️", "star and crescent"),
    ("🕉️", "om"),
    ("☸️", "wheel of dharma"),
    ("✡️", "star of david"),
    ("🔯", "dotted six-pointed star"),
    ("🕎", "menorah"),
    ("☯️", "yin yang"),
    ("☦️", "orthodox cross"),
    ("🛐", "place of worship"),
    ("⛎", "ophiuchus"),
    ("♈", "aries"),
    ("♉", "taurus"),
    ("♊", "gemini"),
    ("♋", "cancer"),
    ("♌", "leo"),
    ("♍", "virgo"),
    ("♎", "libra"),
    ("♏", "scorpio"),
    ("♐", "sagittarius"),
    ("♑", "capricorn"),
    ("♒", "aquarius"),
    ("♓", "pisces"),
    ("🆔", "id"),
    ("⚛️", "atom"),
    ("🉑", "accept"),
    ("☢️", "radioactive"),
    ("☣️", "biohazard"),
    ("📴", "mobile off"),
    ("📳", "vibration mode"),
    ("🈶", "not free of charge"),
    ("🈚", "free of charge"),
    ("🈸", "application"),
    ("🈺", "open for business"),
    ("🈷️", "monthly amount"),
    ("✴️", "eight-pointed star"),
    ("🆚", "vs"),
    ("💮", "white flower"),
    ("🉐", "bargain"),
    ("㊙️", "secret"),
    ("㊗️", "congratulations"),
    ("🈴", "passing grade"),
    ("🈵", "no vacancy"),
    ("🈹", "discount"),
    ("🈲", "prohibited"),
    ("🅰️", "a button"),
    ("🅱️", "b button"),
    ("🆎", "ab button"),
    ("🆑", "cl"),
    ("🅾️", "o button"),
    ("🆘", "sos"),
    ("❌", "cross mark x no"),
    ("⭕", "hollow red circle"),
    ("🛑", "stop sign"),
    ("⛔", "no entry"),
    ("📛", "name badge"),
    ("🚫", "prohibited"),
    ("💯", "hundred points"),
    ("💢", "anger"),
    ("♨️", "hot springs"),
    ("🚷", "no pedestrians"),
    ("🚯", "no littering"),
    ("🚳", "no bicycles"),
    ("🚱", "non-potable water"),
    ("🔞", "under eighteen"),
    ("📵", "no phones"),
    ("🚭", "no smoking"),
    ("❗", "exclamation"),
    ("❕", "white exclamation"),
    ("❓", "question"),
    ("❔", "white question"),
    ("‼️", "double exclamation"),
    ("⁉️", "exclamation question"),
    ("🔅", "dim button"),
    ("🔆", "bright button"),
    ("〽️", "part alternation"),
    ("⚠️", "warning"),
    ("🚸", "children crossing"),
    ("🔱", "trident"),
    ("⚜️", "fleur-de-lis"),
    ("🔰", "japanese beginner"),
    ("♻️", "recycling"),
    ("✅", "check mark button"),
    ("🈯", "reserved"),
    ("💹", "chart increasing yen"),
    ("❇️", "sparkle"),
    ("✳️", "eight-spoked asterisk"),
    ("❎", "cross mark button"),
    ("🌐", "globe meridians"),
    ("💠", "diamond with a dot"),
    ("Ⓜ️", "circled m"),
    ("🌀", "cyclone"),
    ("💤", "zzz"),
    ("🏧", "atm"),
    ("🚾", "wc"),
    ("♿", "wheelchair"),
    ("🅿️", "p button parking"),
    ("🛗", "elevator"),
    ("🈳", "vacancy"),
    ("🈂️", "service charge"),
    ("🛂", "passport"),
    ("🛃", "customs"),
    ("🛄", "baggage"),
    ("🛅", "left luggage"),
    ("🚹", "mens"),
    ("🚺", "womens"),
    ("🚼", "baby"),
    ("⚧", "transgender symbol"),
    ("🚻", "restroom"),
    ("🚮", "litter in bin"),
    ("🎦", "cinema"),
    ("📶", "antenna bars signal"),
    ("🈁", "here"),
    ("🔣", "input symbols"),
    ("ℹ️", "information"),
    ("🔤", "input latin letters"),
    ("🔡", "input latin lowercase"),
    ("🔠", "input latin uppercase"),
    ("🔢", "input numbers"),
    ("🔟", "keycap ten"),
    ("#️⃣", "keycap hash"),
    ("*️⃣", "keycap asterisk"),
    ("0️⃣", "keycap 0"),
    ("1️⃣", "keycap 1"),
    ("2️⃣", "keycap 2"),
    ("3️⃣", "keycap 3"),
    ("4️⃣", "keycap 4"),
    ("5️⃣", "keycap 5"),
    ("6️⃣", "keycap 6"),
    ("7️⃣", "keycap 7"),
    ("8️⃣", "keycap 8"),
    ("9️⃣", "keycap 9"),
    ("⏏️", "eject"),
    ("▶️", "play"),
    ("⏸️", "pause"),
    ("⏯️", "play pause"),
    ("⏹️", "stop button"),
    ("⏺️", "record"),
    ("⏭️", "next track"),
    ("⏮️", "last track"),
    ("⏩", "fast-forward"),
    ("⏪", "fast reverse"),
    ("⏫", "fast up"),
    ("⏬", "fast down"),
    ("◀️", "reverse"),
    ("🔼", "upwards button"),
    ("🔽", "downwards button"),
    ("➡️", "right arrow"),
    ("⬅️", "left arrow"),
    ("⬆️", "up arrow"),
    ("⬇️", "down arrow"),
    ("↗️", "up-right arrow"),
    ("↘️", "down-right arrow"),
    ("↙️", "down-left arrow"),
    ("↖️", "up-left arrow"),
    ("↕️", "up-down arrow"),
    ("↔️", "left-right arrow"),
    ("↪️", "left arrow curving right"),
    ("↩️", "right arrow curving left"),
    ("⤴️", "right arrow curving up"),
    ("⤵️", "right arrow curving down"),
    ("🔀", "shuffle"),
    ("🔁", "repeat"),
    ("🔂", "repeat one"),
    ("🔄", "counterclockwise"),
    ("🔃", "clockwise"),
    ("🎵", "music note"),
    ("🎶", "music notes"),
    ("➕", "plus"),
    ("➖", "minus"),
    ("➗", "divide"),
    ("✖️", "multiply"),
    ("♾️", "infinity"),
    ("💲", "heavy dollar sign"),
    ("💱", "currency exchange"),
    ("™️", "trade mark"),
    ("©️", "copyright"),
    ("®️", "registered"),
    ("👁️‍🗨️", "eye in speech bubble"),
    ("🔚", "end"),
    ("🔙", "back"),
    ("🔛", "on"),
    ("🔝", "top"),
    ("🔜", "soon"),
    ("〰️", "wavy dash"),
    ("➰", "curly loop"),
    ("➿", "double curly loop"),
    ("✔️", "check mark"),
    ("☑️", "check box"),
    ("🔘", "radio button"),
    ("🔴", "red circle"),
    ("🟠", "orange circle"),
    ("🟡", "yellow circle"),
    ("🟢", "green circle"),
    ("🔵", "blue circle"),
    ("🟣", "purple circle"),
    ("⚫", "black circle"),
    ("⚪", "white circle"),
    ("🟤", "brown circle"),
    ("🔺", "red triangle up"),
    ("🔻", "red triangle down"),
    ("🔸", "small orange diamond"),
    ("🔹", "small blue diamond"),
    ("🔶", "large orange diamond"),
    ("🔷", "large blue diamond"),
    ("🔳", "white square button"),
    ("🔲", "black square button"),
    ("▪️", "black small square"),
    ("▫️", "white small square"),
    ("◾", "black medium-small square"),
    ("◽", "white medium-small square"),
    ("◼️", "black medium square"),
    ("◻️", "white medium square"),
    ("⬛", "black large square"),
    ("⬜", "white large square"),
    ("🟥", "red square"),
    ("🟧", "orange square"),
    ("🟨", "yellow square"),
    ("🟩", "green square"),
    ("🟦", "blue square"),
    ("🟪", "purple square"),
    ("🟫", "brown square"),
    ("🔈", "speaker low"),
    ("🔇", "muted speaker"),
    ("🔉", "speaker medium"),
    ("🔊", "speaker high"),
    ("🔔", "bell"),
    ("🔕", "bell with slash"),
    ("📣", "megaphone"),
    ("📢", "loudspeaker"),
    ("💬", "speech balloon"),
    ("💭", "thought balloon"),
    ("♠️", "spade suit"),
    ("♣️", "club suit"),
    ("♥️", "heart suit"),
    ("♦️", "diamond suit"),
    ("🃏", "joker"),
    ("🎴", "flower playing cards"),
    ("🀄", "mahjong"),
    ("🕐", "one oclock"),
    ("🕑", "two oclock"),
    ("🕒", "three oclock"),
    ("🕓", "four oclock"),
    ("🕔", "five oclock"),
    ("🕕", "six oclock"),
    ("🕖", "seven oclock"),
    ("🕗", "eight oclock"),
    ("🕘", "nine oclock"),
    ("🕙", "ten oclock"),
    ("🕚", "eleven oclock"),
    ("🕛", "twelve oclock"),
]:
    add(item[0], "symbols", item[1])

# Flags
FLAGS = [
    ("🇳🇵", "nepal flag country"),
    ("🇮🇳", "india flag country"),
    ("🇺🇸", "united states usa america flag"),
    ("🇬🇧", "united kingdom uk britain flag"),
    ("🇨🇳", "china flag"),
    ("🇯🇵", "japan flag"),
    ("🇰🇷", "south korea flag"),
    ("🇩🇪", "germany flag"),
    ("🇫🇷", "france flag"),
    ("🇮🇹", "italy flag"),
    ("🇪🇸", "spain flag"),
    ("🇧🇷", "brazil flag"),
    ("🇨🇦", "canada flag"),
    ("🇦🇺", "australia flag"),
    ("🇷🇺", "russia flag"),
    ("🇧🇩", "bangladesh flag"),
    ("🇵🇰", "pakistan flag"),
    ("🇱🇰", "sri lanka flag"),
    ("🇧🇹", "bhutan flag"),
    ("🇲🇻", "maldives flag"),
    ("🇦🇫", "afghanistan flag"),
    ("🇦🇪", "united arab emirates flag"),
    ("🇸🇦", "saudi arabia flag"),
    ("🇶🇦", "qatar flag"),
    ("🇰🇼", "kuwait flag"),
    ("🇹🇷", "turkey flag"),
    ("🇮🇷", "iran flag"),
    ("🇮🇱", "israel flag"),
    ("🇪🇬", "egypt flag"),
    ("🇿🇦", "south africa flag"),
    ("🇳🇬", "nigeria flag"),
    ("🇰🇪", "kenya flag"),
    ("🇪🇹", "ethiopia flag"),
    ("🇲🇽", "mexico flag"),
    ("🇦🇷", "argentina flag"),
    ("🇨🇱", "chile flag"),
    ("🇨🇴", "colombia flag"),
    ("🇵🇪", "peru flag"),
    ("🇳🇿", "new zealand flag"),
    ("🇸🇬", "singapore flag"),
    ("🇲🇾", "malaysia flag"),
    ("🇹🇭", "thailand flag"),
    ("🇻🇳", "vietnam flag"),
    ("🇮🇩", "indonesia flag"),
    ("🇵🇭", "philippines flag"),
    ("🇲🇲", "myanmar flag"),
    ("🇰🇭", "cambodia flag"),
    ("🇱🇦", "laos flag"),
    ("🇲🇳", "mongolia flag"),
    ("🇺🇦", "ukraine flag"),
    ("🇵🇱", "poland flag"),
    ("🇳🇱", "netherlands flag"),
    ("🇧🇪", "belgium flag"),
    ("🇨🇭", "switzerland flag"),
    ("🇸🇪", "sweden flag"),
    ("🇳🇴", "norway flag"),
    ("🇩🇰", "denmark flag"),
    ("🇫🇮", "finland flag"),
    ("🇮🇪", "ireland flag"),
    ("🇵🇹", "portugal flag"),
    ("🇬🇷", "greece flag"),
    ("🏳️", "white flag"),
    ("🏴", "black flag"),
    ("🏁", "chequered flag race"),
    ("🚩", "triangular flag"),
    ("🏳️‍🌈", "rainbow flag pride"),
    ("🏳️‍⚧️", "transgender flag"),
    ("🇺🇳", "united nations flag"),
]
for glyph, keywords in FLAGS:
    add(glyph, "flags", keywords)

# Ensure original catalog glyphs remain present
for glyph, category, keywords in [
    ("😀", "smileys", "grinning happy smile"),
    ("😊", "smileys", "blush smile happy"),
    ("🐶", "animals", "dog puppy pet"),
    ("🍎", "food", "apple fruit food"),
]:
    if not any(row[0] == glyph for row in RAW):
        add(glyph, category, keywords)


def main():
    seen = set()
    lines = [
        "# glyph<TAB>category<TAB>keywords<TAB>variants",
        "# Offline Unicode emoji catalog. Rebuild with scripts/build_emoji_catalog.py",
        "",
    ]
    for glyph, category, keywords, variants in RAW:
        key = (glyph, category)
        if key in seen or not glyph.strip():
            continue
        seen.add(key)
        lines.append(f"{glyph}\t{category}\t{keywords}\t{variants}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(seen)} emoji rows to {OUT}")


if __name__ == "__main__":
    main()
